# Generated by Django 3.0.4 on 2020-04-15 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0002_auto_20200403_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frame',
            old_name='d_début',
            new_name='d_debut',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='d_debut_match',
            new_name='d_debut',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='d_fin_match',
            new_name='d_fin',
        ),
    ]
