# Generated by Django 3.0.4 on 2020-04-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0006_remove_jeuvariantes_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueur',
            name='joueur_actif',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
