# Generated by Django 3.0.4 on 2020-04-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0007_joueur_joueur_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeuvariantes',
            name='code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
