# Generated by Django 3.0.4 on 2020-04-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0008_jeuvariantes_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jeuvariantes',
            name='code',
        ),
        migrations.AddField(
            model_name='match',
            name='distanceFR_j1',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='distanceFR_j2',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
