# Generated by Django 3.0.5 on 2020-04-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0010_eventtype_frameevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frameevent',
            name='points',
            field=models.SmallIntegerField(blank=True),
        ),
    ]
