# Generated by Django 3.0.5 on 2020-04-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0011_auto_20200427_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frameevent',
            name='points',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
