# Generated by Django 3.0.5 on 2020-04-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0012_auto_20200427_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame',
            name='score_reprise',
        ),
        migrations.RemoveField(
            model_name='frame',
            name='scoref_j1',
        ),
        migrations.RemoveField(
            model_name='frame',
            name='scoref_j2',
        ),
        migrations.AlterField(
            model_name='frame',
            name='d_debut',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='scorem_j1',
            field=models.SmallIntegerField(blank=True, db_column='scoreM_J1', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='scorem_j2',
            field=models.SmallIntegerField(blank=True, db_column='scoreM_J2', default=0, null=True),
        ),
    ]
