# Generated by Django 3.0.5 on 2020-04-29 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0014_auto_20200429_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame',
            name='status',
        ),
    ]
