# Generated by Django 3.0.5 on 2020-05-01 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0015_remove_frame_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='en_cours',
        ),
        migrations.RemoveField(
            model_name='match',
            name='scorem_j1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='scorem_j2',
        ),
    ]
