# Generated by Django 3.0.5 on 2020-05-02 09:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0016_auto_20200501_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='d_debut',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='laissez la valeur par défaut pour un démarrage immédiat', verbose_name='Début du match'),
        ),
        migrations.AlterField(
            model_name='match',
            name='distanceFR_j1',
            field=models.SmallIntegerField(blank=True, help_text='Optionnel, ne concerne que la carambole', null=True, verbose_name='Distance joueur 1'),
        ),
        migrations.AlterField(
            model_name='match',
            name='distanceFR_j2',
            field=models.SmallIntegerField(blank=True, help_text='Optionnel, ne concerne que la carambole', null=True, verbose_name='Distance joueur 2'),
        ),
        migrations.AlterField(
            model_name='match',
            name='jeu_type',
            field=models.CharField(choices=[('fr', 'Carambole'), ('sn', 'Snooker'), ('po', 'Pool'), ('us', 'Américain')], default='fr', max_length=2, verbose_name='Type de jeu'),
        ),
        migrations.AlterField(
            model_name='match',
            name='jeu_variante',
            field=models.ForeignKey(db_column='Jeu_Variantes_id', on_delete=django.db.models.deletion.PROTECT, to='gestionnaire.JeuVariantes', verbose_name='Variante de jeu'),
        ),
        migrations.AlterField(
            model_name='match',
            name='joueur1',
            field=models.ForeignKey(db_column='joueur1_id', on_delete=django.db.models.deletion.PROTECT, related_name='joueur1', to='gestionnaire.Joueur', verbose_name='Joueur 1'),
        ),
        migrations.AlterField(
            model_name='match',
            name='joueur2',
            field=models.ForeignKey(db_column='joueur2_id', on_delete=django.db.models.deletion.PROTECT, related_name='joueur2', to='gestionnaire.Joueur', verbose_name='Joueur 2'),
        ),
        migrations.AlterField(
            model_name='match',
            name='nb_frames',
            field=models.SmallIntegerField(default=1, help_text='Nombre de frames maximum à jouer dans ce match', verbose_name='Nombre de frames'),
        ),
    ]
