# Generated by Django 3.0.5 on 2020-05-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0017_auto_20200502_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='numéro',
            field=models.SmallIntegerField(default=1, null=True, verbose_name='Numéro de la frame dans le match'),
        ),
    ]
