# Generated by Django 3.0.5 on 2020-05-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0018_frame_numéro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='numéro',
            field=models.SmallIntegerField(default=1, verbose_name='Numéro de la frame dans le match'),
        ),
    ]
