# Generated by Django 3.0.5 on 2020-05-02 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0019_auto_20200502_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frame',
            old_name='numéro',
            new_name='num',
        ),
    ]
