# Generated by Django 3.0.5 on 2020-05-04 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0021_match_toss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='toss',
        ),
        migrations.AlterField(
            model_name='match',
            name='d_debut',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='laissez la valeur par défaut pour un démarrage immédiat', null=True, verbose_name='Début du match'),
        ),
    ]
