# Generated by Django 3.0.5 on 2020-05-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0027_auto_20200514_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='num',
            field=models.SmallIntegerField(default=1, verbose_name='N° de frame dans le match'),
        ),
    ]
