# Generated by Django 3.0.5 on 2020-05-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0028_auto_20200525_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='shot_time_limit',
            field=models.SmallIntegerField(blank=True, default=0, help_text='Durée maximum pour réaliser un coup (vide = pas de limite)', null=True, verbose_name='Temps max par coup (sec)'),
        ),
    ]
