# Generated by Django 3.0.5 on 2020-05-25 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0029_match_shot_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='nb_frames',
            field=models.SmallIntegerField(default=3, help_text='Nombre de frames maximum à jouer dans ce match', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Nombre de frames'),
        ),
        migrations.AlterField(
            model_name='match',
            name='shot_time_limit',
            field=models.SmallIntegerField(blank=True, default=0, help_text='Durée maximum pour réaliser un coup (0 = pas de limite)', null=True, verbose_name='Temps max par coup (sec)'),
        ),
    ]
