# Generated by Django 3.0.5 on 2020-05-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0030_auto_20200525_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='nb_frames',
            field=models.SmallIntegerField(default=3, help_text='Nombre de frames maximum à jouer dans ce match', verbose_name='Nombre de frames'),
        ),
    ]
