# Generated by Django 3.0.5 on 2020-05-26 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0031_auto_20200525_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='nb_frames',
            field=models.SmallIntegerField(default=3, help_text='Nombre de frames maximum à jouer dans ce match', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Nombre de frames'),
        ),
    ]
