# Generated by Django 3.0.5 on 2020-05-27 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0032_auto_20200526_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeuvariantes',
            name='jeu_type',
            field=models.CharField(choices=[('fr', 'Carambole'), ('sn', 'Snooker'), ('po', 'Pool'), ('us', 'Américain')], default='fr', max_length=2, verbose_name='Type de jeu'),
        ),
        migrations.AlterField(
            model_name='match',
            name='fr_distance_j1',
            field=models.SmallIntegerField(blank=True, default=10, help_text='Optionnel, ne concerne que la carambole', null=True, validators=[django.core.validators.MinValueValidator(1, message='La distance doit être un nombre positif')], verbose_name='Distance joueur 1'),
        ),
        migrations.AlterField(
            model_name='match',
            name='fr_distance_j2',
            field=models.SmallIntegerField(blank=True, default=10, help_text='Optionnel, ne concerne que la carambole', null=True, validators=[django.core.validators.MinValueValidator(1, message='La distance doit être un nombre positif')], verbose_name='Distance joueur 2'),
        ),
        migrations.AlterField(
            model_name='match',
            name='fr_limite_nb_reprises',
            field=models.SmallIntegerField(blank=True, default=10, help_text='Optionnel, ne concerne que la carambole', null=True, validators=[django.core.validators.MinValueValidator(1, message='Le nombre de reprises doit être un nombre positif')], verbose_name='Limite du nombre de reprises'),
        ),
        migrations.AlterField(
            model_name='match',
            name='nb_frames',
            field=models.SmallIntegerField(default=3, help_text='Nombre de frames maximum à jouer dans ce match', validators=[django.core.validators.MaxValueValidator(100, message='Le nombre de frame doit être inférieur à 100'), django.core.validators.MinValueValidator(1, message='Le nombre de frame doit être supérieur ou égal à 1')], verbose_name='Nombre de frames'),
        ),
        migrations.AlterField(
            model_name='match',
            name='shot_time_limit',
            field=models.SmallIntegerField(blank=True, default=0, help_text='Durée maximum pour réaliser un coup (0 = pas de limite)', null=True, validators=[django.core.validators.MinValueValidator(0, message='Le temps doit être un nombre positif')], verbose_name='Temps max par coup (sec)'),
        ),
    ]
