# Generated by Django 3.0.5 on 2020-06-04 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0034_jeuvariantes_ordre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='fr_distance_j1',
            field=models.SmallIntegerField(blank=True, default=10, help_text='Optionnel, ne concerne que la carambole', null=True, validators=[django.core.validators.MinValueValidator(0, message='La distance doit être un nombre positif')], verbose_name='Distance joueur 1'),
        ),
        migrations.AlterField(
            model_name='match',
            name='fr_distance_j2',
            field=models.SmallIntegerField(blank=True, default=10, help_text='Optionnel, ne concerne que la carambole', null=True, validators=[django.core.validators.MinValueValidator(0, message='La distance doit être un nombre positif')], verbose_name='Distance joueur 2'),
        ),
        migrations.AlterField(
            model_name='match',
            name='fr_limite_nb_reprises',
            field=models.SmallIntegerField(blank=True, default=10, help_text='Optionnel, ne concerne que la carambole', null=True, validators=[django.core.validators.MinValueValidator(0, message='Le nombre de reprises doit être un nombre positif')], verbose_name='Limite du nombre de reprises'),
        ),
        migrations.AlterField(
            model_name='match',
            name='jeu_type',
            field=models.CharField(choices=[('fr', 'Carambole'), ('sn', 'Snooker'), ('po', 'Pool'), ('us', 'Américain')], default='sn', max_length=2, verbose_name='Type de jeu'),
        ),
    ]
