# Generated by Django 3.0.4 on 2020-04-15 16:02

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0004_auto_20200415_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueur',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=100, populate_from=('id', 'nom', 'prenom'), unique=True),
        ),
    ]
