# Generated by Django 3.0.4 on 2020-04-15 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0009_joueur_slugii'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joueur',
            name='slugii',
        ),
    ]
