# Generated by Django 3.0.4 on 2020-04-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='jeu_variantes',
            new_name='jeu_variante',
        ),
        migrations.AlterField(
            model_name='jeuvariantes',
            name='regles_url',
            field=models.URLField(blank=True, help_text='Permet de renvoyer vers un site décrivant les règles', verbose_name='Lien vers les règles'),
        ),
    ]
