# Generated by Django 3.0.4 on 2020-04-16 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0004_auto_20200415_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frame',
            options={'verbose_name_plural': 'FrameModel'},
        ),
        migrations.AlterModelOptions(
            name='jeuvariantes',
            options={'verbose_name_plural': 'JeuVariantesModel'},
        ),
        migrations.AlterModelOptions(
            name='joueur',
            options={'verbose_name_plural': 'JoueurModel'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-d_fin'], 'verbose_name_plural': 'MatchModel'},
        ),
    ]
