# Generated by Django 3.0.4 on 2020-04-17 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0005_auto_20200416_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jeuvariantes',
            name='code',
        ),
    ]
