# Generated by Django 3.0.4 on 2020-04-15 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0005_joueur_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joueur',
            name='slug',
        ),
    ]
